### ISSUE TITLE
Installing Requirements

### ISSUE THREAD

**Issue by formeo14** [thomasvandermars/faster-rcnn-object-detection#1]
I am attempting to execute the Jupyter notebook using miniconda3, but I am encountering some issues with the code. Specifically, I am having trouble installing the packages listed in the requirements.txt file. The installation process consistently fails, as illustrated by the following example:

```
Using cached matplotlib-3.4.3.tar.gz (37.9 MB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
```

Could you please advise if there is a specific procedure I should follow when installing these packages via pip? I would greatly appreciate any guidance you can provide to resolve this issue.

**Comment by thomasvandermars** [comment]
Hello formeo14,

First of all, my apologies that you are experiencing issues with the installing requirements. I have found a pretty good website that walks you through dealing with this error: https://sebhastian.com/python-error-subprocess-exited-with-error/.

According to this website the "most common causes for this error are:

1.) A required build tool is missing
2.) The package doesn’t support the operating system you’re using
3.) The package doesn’t support the latest Python version
4.) The package may require additional steps to install

The cause for this error is usually written in the log a few lines above or below it, so you need to read the standard output carefully."

Addressing the probable causes:

1.) I have just re-generated and uploaded a complete (unaltered) version of the requirements.txt file. It probably has some redundant packages. However, I am now certain that it has all the packages required.

2.) I have used Windows 11 when creating this project. Unfortunately, I cannot test if it there are compatibility issues with macOS.

3.) When it is a support issue, the error message will have something like this "RuntimeError: Cannot install on Python version 3.11.2". I have used Python 3.9.15 to create this project.

Hopefully, this is helpful. If the issue persists, please share more of the error message as it will likely point us in the right direction.

**Comment by formeo14** [comment]
Thank you the requirements.txt works now.
Only sklearn==0.0.post1 did throw an error again but I could solve that with installing scikit-learn and then run requirements.txt again.
